import { Inter } from "next/font/google";
import Header from '../components/header';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <head>
              <title>Mi Aplicación</title>
          </head>
          <body className="bg-gray-100 flex flex-col min-h-screen">
              <Header/>
              <main  className="flex flex-1 justify-center items-center">
                  {children}
              </main>
        </body>
      </html>
  );
}
